[package]
name = "axe"
version = "0.1.0-alpha.1"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/taytrix/axe"
description = "axe: by this axe I rule. Cross-platform Conan Exiles Enhanced server CLI."
readme = false

[lib]
name = "axe"
path = "src/lib.rs"

[[bin]]
name = "axe"
path = "src/main.rs"

[dependencies]
camino = { version = "1", features = ["serde1"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive", "env"] }
humantime-serde = "1"
keyvalues-parser = "0.2"
owo-colors = { version = "4", features = ["supports-colors"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
toml = "0.9"
ureq = { version = "3", features = ["json"] }

[dev-dependencies]
tempfile = "3"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
