[package]
name = "axe-service-gen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Generators for systemd units and Windows Task Scheduler XML."

[dependencies]
axe-core.workspace = true
anyhow.workspace = true
serde.workspace = true
